Some laptop specific things

diff --git a/bspwm/.config/bspwm/bspwmrc b/bspwm/.config/bspwm/bspwmrc
--- a/bspwm/.config/bspwm/bspwmrc
+++ b/bspwm/.config/bspwm/bspwmrc
@@ -19,22 +19,21 @@ fi
 sleep 1; compton -b
 /home/dief/.config/polybar/launch.sh &
 nm-applet &
-blueman-applet &
+#blueman-applet &
 xautolock -time 10 -locker /home/dief/.local/bin/lock &
 #ff-theme-util &
 #fix_xcursor &
 /home/dief/.local/share/tresorit/tresorit --hidden &
-redshift &
 
 if [[ "$host" == "shinobi" ]]
 then
     cbatticon &
     #pasystray &
     #amixer set Capture toggle
-    until dunst; do
-        echo "'dunst' crashed with exit code $?.  Respawning.." >&2
-        sleep 1
-    done
+    #until dunst; do
+        #echo "'dunst' crashed with exit code $?.  Respawning.." >&2
+        #sleep 1
+    #done
 fi
 
 if [[ "$host" == "samurai" ]]
